services:
  db:
    image: postgres:15
    container_name: stk-techical-test-db-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menus_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: menu-backend
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234567
      - DB_NAME=db
      - DB_SSL=false
    ports:
      - "3000:3000" 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: menu-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
    ports:
      - "3001:3000"

volumes:
  db_data:
